### ISSUE TITLE
CSU10 – Cancelar Compra

### ISSUE THREAD

**Issue by rafaelmereb** [daniel-oliveiravas/SVRI#10]
Atores: Cliente
Categoria: Secundário
Descrição:
Após a comprar ter sido registrada e estiver em processamento, na fase pendente, pelo sistema, o usuário pode optar pelo seu cancelamento. Acessando um menu que contém todas as compras feitas, o usuário pode selecionar uma compra específica e então pode optar pelo seu cancelamento, contanto que ela ainda esteja em fase de processamento(pendente) pela forma de pagamento selecionada. Caso ela já tenha sido concretizada, não há como cancelar a compra. Esse cancelamento não produz nenhum ônus para o usuário, nem qualquer tipo de taxa, e deve ser confirmado antes de ser feito para garantir que não seja um erro por parte do usuário.

**Comment by Yuri-M-Dias** [comment]
Lembrete trimestral de que o Lucas não voltou.
