### ISSUE TITLE
CSU11 – Gerar Links para as Páginas

### ISSUE THREAD

**Issue by rafaelmereb** [daniel-oliveiravas/SVRI#11]
Atores: Administrador
Categoria: Secundário
Descrição:
No momento em que uma atração for cadastrada no sistema, o sistema deve gerar um endereço (link) para sua página correspondente à compra de ingressos para sessões daquela atração. Isso, para permitir que o portal (site) do administrador do estabelecimento de atrações (administrador do cinema ou do teatro) integre o link da compra da atração em sua página de atrações, de modo que quando o usuário clicar em comprar ingresso para ma atração, será redirecionado para a página da atração no SVRI, para comprar seu ingresso (a página contendo um conjunto de sessões para aquela atração). De maneira análoga, o sistema deve gerar um link para acesso a sua página específica de uma sessão de uma atração, de modo que outro sistema possa usar esse link, quando um usuário escolher uma sessão de uma atração e quiser comprar, redirecionando para a página no SVRI de compra do ingresso para a sessão da atração escolhida. O sistema também precisa gerar o link para sua página que contém todas as atrações em cartaz disponíveis para compra de ingressos (página de atrações).

**Comment by Yuri-M-Dias** [comment]
Sprint acabou.
