### ISSUE TITLE
CSU2 – Manter Cadastro de Assentos

### ISSUE THREAD

**Issue by rafaelmereb** [daniel-oliveiravas/SVRI#2]
Atores: Funcionário do Estabelecimento
Categoria: Primário
Descrição:
O caso de uso Cadastrar  Assentos acontece quando o funcionário responsável pelo estabelecimento onde o sistema irá ser implantado, realiza o cadastro um novo assento. Esté assento será exibido na tela de cadastro de sala para configuração da mesma. Os assentos exigem particularidades como o nome ou identificação do mesmo, e o índice do preço do ingresso, como por exemplo, uma assento especial pode ser mais cara que um assento normal, ou, da mesma forma, um assento especial pode ser mais barato que um assento normal, devido a particularidades atribuídas pelo responsável pelo cadastro do assento.

**Comment by Yuri-M-Dias** [comment]
Lucas ainda não voltou!
